apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: postgres-pv-volume
  namespace: dmp-local
  labels:
    type: local
    app: postgres-pv-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath: # hostPath PersistentVolume is used for development and testing. It uses a file/directory on the Node to emulate network-attached storage
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain # Retain the PV even after PVC is deleted.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: dmp-local
  labels:
    app: postgres-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: kong-postgres-svc
  namespace: dmp-local
  labels: # Labels that will be applied to the resource
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: dmp-local
  labels:
    app: postgres
data:
  POSTGRES_DB: api_gateway
  POSTGRES_USER: mbiz
  POSTGRES_PASSWORD: mbiz
  KONG_PG_HOST: kong-postgres-svc
  KONG_PG_DATABASE: api_gateway
  KONG_PG_USER: mbiz
  KONG_PG_PASSWORD: mbiz

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: dmp-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: kong-postgres
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
