apiVersion: apps/v1
kind: Deployment
metadata:
  name: radiance-local
  namespace: dmp-local
  labels:
    app.kubernetes.io/name: radiance-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radiance-k8s
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radiance-local
    spec:
      containers:
        - name: radiance-local
          image: radiance-k8s
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8080"
            - name: DATABASE_TYPE
              value: "mysql"
            - name: DATABASE_HOST
              value: "10.100.154.17"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: "dmp"
            - name: USERNAME_DB
              value: "mbiz_dmp"
            - name: PASSWORD_DB
              value: "K3iVeequee5uo7m"
            - name: DMP_EXCHANGE
              value: "dmp_event"
            - name: RABBIT_HOST
              value: "10.100.154.20"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: "admin"
            - name: RABBIT_PASSWORD
              value: "koorooX5eeghiaf"
