apiVersion: apps/v1
kind: Deployment
metadata:
  name: radiance-local
  namespace: dmp-local
  labels:
    app.kubernetes.io/name: radiance-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radiance-local
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radiance-local
    spec:
      containers:
        - name: radiance-local
          image: radiance-k8s
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: global-env
            - configMapRef:
                name: radiance-env
